sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t belf33/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true belf33/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    name: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-526390243088"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"